<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BaseOutputPath></BaseOutputPath>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.0" />
    <PackageReference Include="CloudinaryDotNet" Version="1.27.4" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="DinkToPdf.Standard" Version="1.1.0" />
    <PackageReference Include="Google.Apis.Auth" Version="1.68.0" />
    <PackageReference Include="itext7" Version="9.1.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="MailKit" Version="4.10.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="9.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.3" />
    <PackageReference Include="MimeKit" Version="4.10.0" />
    <PackageReference Include="payOS" Version="1.0.9" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.9.0" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.3" />
    <PackageReference Include="TimeZoneConverter" Version="6.1.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.10" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.13" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\STP.Repository\STP.Repository.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\movie_ticket_clean.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>