// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using STP.Repository.Data;

#nullable disable

namespace STP.Repository.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20260924152721_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("STP.Repository.Models.BookingHistory", b =>
                {
                    b.Property<int>("Booking_History_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Booking_History_ID"));

                    b.Property<int>("Booking_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Booking_History_ID");

                    b.HasIndex("Booking_ID");

                    b.ToTable("Booking_History", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.CinemaRoom", b =>
                {
                    b.Property<int>("Cinema_Room_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Cinema_Room_ID"));

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Room_Name")
                        .HasColumnType("text");

                    b.Property<string>("Room_Type")
                        .HasColumnType("text");

                    b.Property<int>("Seat_Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Cinema_Room_ID");

                    b.ToTable("Cinema_Rooms", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.FailedLogin", b =>
                {
                    b.Property<int>("FailedLogin_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FailedLogin_ID"));

                    b.Property<DateTime>("AttemptTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IP_Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("FailedLogin_ID");

                    b.HasIndex("AttemptTime");

                    b.HasIndex("User_ID");

                    b.ToTable("FailedLogins");
                });

            modelBuilder.Entity("STP.Repository.Models.Movie", b =>
                {
                    b.Property<int>("Movie_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Movie_ID"));

                    b.Property<string>("Cast")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Created_By")
                        .HasColumnType("integer");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Movie_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Poster_URL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Production_Company")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trailer_Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Movie_ID");

                    b.HasIndex("Created_By");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.MovieRating", b =>
                {
                    b.Property<int>("Rating_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Rating_ID"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Is_Verified")
                        .HasColumnType("boolean");

                    b.Property<int>("Movie_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Rating_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("Rating_ID");

                    b.HasIndex("Movie_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Movie_Ratings", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.Payment", b =>
                {
                    b.Property<int>("Payment_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Payment_ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Booking_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Payment_Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Payment_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Processed_By")
                        .HasColumnType("integer");

                    b.Property<string>("Processor_Response")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Refund_Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("Refund_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Refund_Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Transaction_Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Payment_ID");

                    b.HasIndex("Booking_ID");

                    b.HasIndex("Processed_By");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.PointsEarning", b =>
                {
                    b.Property<int>("Earning_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Earning_ID"));

                    b.Property<decimal>("Actual_Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Booking_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points_Earned")
                        .HasColumnType("integer");

                    b.Property<int>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("Earning_ID");

                    b.HasIndex("Booking_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Points_Earning", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.PointsRedemption", b =>
                {
                    b.Property<int>("Redemption_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Redemption_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points_Redeemed")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("Redemption_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Points_Redemption", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.Promotion", b =>
                {
                    b.Property<int>("Promotion_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Promotion_ID"));

                    b.Property<string>("Applicable_For")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Created_By")
                        .HasColumnType("integer");

                    b.Property<int>("Current_Usage")
                        .HasColumnType("integer");

                    b.Property<string>("Discount_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Discount_Value")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Maximum_Discount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Minimum_Purchase")
                        .HasColumnType("numeric");

                    b.Property<string>("Promotion_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Promotion_Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Usage_Limit")
                        .HasColumnType("integer");

                    b.HasKey("Promotion_ID");

                    b.HasIndex("Created_By");

                    b.HasIndex("Promotion_Code")
                        .IsUnique();

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.PromotionUsage", b =>
                {
                    b.Property<int>("Usage_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Usage_ID"));

                    b.Property<DateTime>("Applied_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Booking_ID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Discount_Amount")
                        .HasColumnType("numeric");

                    b.Property<bool>("HasUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Promotion_ID")
                        .HasColumnType("integer");

                    b.Property<int>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("Usage_ID");

                    b.HasIndex("Booking_ID");

                    b.HasIndex("Promotion_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Promotion_Usage", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.Score", b =>
                {
                    b.Property<int>("Score_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Score_ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points_Added")
                        .HasColumnType("integer");

                    b.Property<int>("Points_Used")
                        .HasColumnType("integer");

                    b.Property<int>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("Score_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Scores", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.Seat", b =>
                {
                    b.Property<int>("Seat_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Seat_ID"));

                    b.Property<int?>("Booking_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Last_Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Layout_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Seat_Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Showtime_ID")
                        .HasColumnType("integer");

                    b.HasKey("Seat_ID");

                    b.HasIndex("Booking_ID");

                    b.HasIndex("Layout_ID");

                    b.HasIndex("Showtime_ID");

                    b.ToTable("Seats", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.SeatLayout", b =>
                {
                    b.Property<int>("Layout_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Layout_ID"));

                    b.Property<int>("Cinema_Room_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Column_Number")
                        .HasColumnType("integer");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Row_Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Seat_Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Layout_ID");

                    b.HasIndex("Cinema_Room_ID");

                    b.ToTable("Seat_Layout", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.Showtime", b =>
                {
                    b.Property<int>("Showtime_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Showtime_ID"));

                    b.Property<decimal>("Base_Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Capacity_Available")
                        .HasColumnType("integer");

                    b.Property<int>("Cinema_Room_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Created_By")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("End_Time")
                        .HasColumnType("interval");

                    b.Property<int>("Movie_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Price_Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Show_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Start_Time")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated_At")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Showtime_ID");

                    b.HasIndex("Cinema_Room_ID");

                    b.HasIndex("Created_By");

                    b.HasIndex("Movie_ID");

                    b.ToTable("Showtimes", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.Ticket", b =>
                {
                    b.Property<int>("Ticket_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Ticket_ID"));

                    b.Property<decimal>("Base_Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Booking_ID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Check_In_Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount_Amount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Final_Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("Is_Checked_In")
                        .HasColumnType("boolean");

                    b.Property<int>("Seat_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Ticket_Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Ticket_ID");

                    b.HasIndex("Booking_ID");

                    b.HasIndex("Seat_ID");

                    b.HasIndex("Ticket_Code")
                        .IsUnique();

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.TicketBooking", b =>
                {
                    b.Property<int>("Booking_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Booking_ID"));

                    b.Property<DateTime>("Booking_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Created_By")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Payment_Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Points_Earned")
                        .HasColumnType("integer");

                    b.Property<int>("Points_Used")
                        .HasColumnType("integer");

                    b.Property<int?>("Promotion_ID")
                        .HasColumnType("integer");

                    b.Property<int>("Showtime_ID")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total_Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("Booking_ID");

                    b.HasIndex("Created_By");

                    b.HasIndex("Promotion_ID");

                    b.HasIndex("Showtime_ID");

                    b.HasIndex("User_ID");

                    b.ToTable("Ticket_Bookings", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.TicketPricing", b =>
                {
                    b.Property<int>("Price_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Price_ID"));

                    b.Property<decimal>("Base_Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Last_Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Room_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Seat_Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Price_ID");

                    b.HasIndex("Room_Type", "Seat_Type")
                        .IsUnique();

                    b.ToTable("Ticket_Pricing", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.User", b =>
                {
                    b.Property<int>("User_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("User_ID"));

                    b.Property<string>("Account_Status")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Date_Of_Birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Full_Name")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Hire_Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Last_Login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Phone_Number")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Sex")
                        .HasColumnType("text");

                    b.HasKey("User_ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.UserPoints", b =>
                {
                    b.Property<int>("UserPoints_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserPoints_ID"));

                    b.Property<DateTime>("Last_Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Total_Points")
                        .HasColumnType("integer");

                    b.Property<int>("User_ID")
                        .HasColumnType("integer");

                    b.HasKey("UserPoints_ID");

                    b.HasIndex("User_ID")
                        .IsUnique();

                    b.ToTable("User_Points", (string)null);
                });

            modelBuilder.Entity("STP.Repository.Models.BookingHistory", b =>
                {
                    b.HasOne("STP.Repository.Models.TicketBooking", "TicketBooking")
                        .WithMany("BookingHistories")
                        .HasForeignKey("Booking_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketBooking");
                });

            modelBuilder.Entity("STP.Repository.Models.Movie", b =>
                {
                    b.HasOne("STP.Repository.Models.User", "CreatedBy")
                        .WithMany("Movies")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("STP.Repository.Models.MovieRating", b =>
                {
                    b.HasOne("STP.Repository.Models.Movie", "Movie")
                        .WithMany("MovieRatings")
                        .HasForeignKey("Movie_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.User", "User")
                        .WithMany("MovieRatings")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STP.Repository.Models.Payment", b =>
                {
                    b.HasOne("STP.Repository.Models.TicketBooking", "TicketBooking")
                        .WithMany("Payments")
                        .HasForeignKey("Booking_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.User", "ProcessedBy")
                        .WithMany("ProcessedPayments")
                        .HasForeignKey("Processed_By")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProcessedBy");

                    b.Navigation("TicketBooking");
                });

            modelBuilder.Entity("STP.Repository.Models.PointsEarning", b =>
                {
                    b.HasOne("STP.Repository.Models.TicketBooking", "TicketBooking")
                        .WithMany()
                        .HasForeignKey("Booking_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketBooking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STP.Repository.Models.PointsRedemption", b =>
                {
                    b.HasOne("STP.Repository.Models.User", "User")
                        .WithMany("PointsRedemptions")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STP.Repository.Models.Promotion", b =>
                {
                    b.HasOne("STP.Repository.Models.User", "CreatedBy")
                        .WithMany("Promotions")
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("STP.Repository.Models.PromotionUsage", b =>
                {
                    b.HasOne("STP.Repository.Models.TicketBooking", "TicketBooking")
                        .WithMany("PromotionUsages")
                        .HasForeignKey("Booking_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.Promotion", "Promotion")
                        .WithMany("PromotionUsages")
                        .HasForeignKey("Promotion_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.User", "User")
                        .WithMany("PromotionUsages")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("TicketBooking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STP.Repository.Models.Score", b =>
                {
                    b.HasOne("STP.Repository.Models.User", "User")
                        .WithMany("Scores")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STP.Repository.Models.Seat", b =>
                {
                    b.HasOne("STP.Repository.Models.TicketBooking", "TicketBooking")
                        .WithMany("Seats")
                        .HasForeignKey("Booking_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("STP.Repository.Models.SeatLayout", "SeatLayout")
                        .WithMany("Seats")
                        .HasForeignKey("Layout_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.Showtime", "Showtime")
                        .WithMany("Seats")
                        .HasForeignKey("Showtime_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SeatLayout");

                    b.Navigation("Showtime");

                    b.Navigation("TicketBooking");
                });

            modelBuilder.Entity("STP.Repository.Models.SeatLayout", b =>
                {
                    b.HasOne("STP.Repository.Models.CinemaRoom", "CinemaRoom")
                        .WithMany("SeatLayouts")
                        .HasForeignKey("Cinema_Room_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaRoom");
                });

            modelBuilder.Entity("STP.Repository.Models.Showtime", b =>
                {
                    b.HasOne("STP.Repository.Models.CinemaRoom", "CinemaRoom")
                        .WithMany("Showtimes")
                        .HasForeignKey("Cinema_Room_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.Movie", "Movie")
                        .WithMany("Showtimes")
                        .HasForeignKey("Movie_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CinemaRoom");

                    b.Navigation("CreatedBy");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("STP.Repository.Models.Ticket", b =>
                {
                    b.HasOne("STP.Repository.Models.TicketBooking", "TicketBooking")
                        .WithMany("Tickets")
                        .HasForeignKey("Booking_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.Seat", "Seat")
                        .WithMany("Tickets")
                        .HasForeignKey("Seat_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seat");

                    b.Navigation("TicketBooking");
                });

            modelBuilder.Entity("STP.Repository.Models.TicketBooking", b =>
                {
                    b.HasOne("STP.Repository.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("Created_By")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.Promotion", "Promotion")
                        .WithMany("TicketBookings")
                        .HasForeignKey("Promotion_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("STP.Repository.Models.Showtime", "Showtime")
                        .WithMany("TicketBookings")
                        .HasForeignKey("Showtime_ID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STP.Repository.Models.User", "User")
                        .WithMany("TicketBookings")
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedBy");

                    b.Navigation("Promotion");

                    b.Navigation("Showtime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("STP.Repository.Models.UserPoints", b =>
                {
                    b.HasOne("STP.Repository.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("User_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("STP.Repository.Models.CinemaRoom", b =>
                {
                    b.Navigation("SeatLayouts");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("STP.Repository.Models.Movie", b =>
                {
                    b.Navigation("MovieRatings");

                    b.Navigation("Showtimes");
                });

            modelBuilder.Entity("STP.Repository.Models.Promotion", b =>
                {
                    b.Navigation("PromotionUsages");

                    b.Navigation("TicketBookings");
                });

            modelBuilder.Entity("STP.Repository.Models.Seat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("STP.Repository.Models.SeatLayout", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("STP.Repository.Models.Showtime", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("TicketBookings");
                });

            modelBuilder.Entity("STP.Repository.Models.TicketBooking", b =>
                {
                    b.Navigation("BookingHistories");

                    b.Navigation("Payments");

                    b.Navigation("PromotionUsages");

                    b.Navigation("Seats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("STP.Repository.Models.User", b =>
                {
                    b.Navigation("MovieRatings");

                    b.Navigation("Movies");

                    b.Navigation("PointsRedemptions");

                    b.Navigation("ProcessedPayments");

                    b.Navigation("PromotionUsages");

                    b.Navigation("Promotions");

                    b.Navigation("Scores");

                    b.Navigation("TicketBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
